import os

output_file = "setup-ai-team.sh"
cwd = os.getcwd()

header = """#!/bin/bash

# AI Team Setup Script
# Generated by Antigravity

echo "🚀 Installing AI Development Team..."

# Create directories
mkdir -p agents/configs
mkdir -p agents/prompts
mkdir -p agents/specializations/saas
mkdir -p agents/specializations/shopify
mkdir -p agents/specializations/mobile
mkdir -p agents/specializations/chrome-extension
mkdir -p agents/specializations/ai-app
mkdir -p agents/specializations/ecommerce
mkdir -p workflows
mkdir -p docs/product docs/architecture docs/database docs/design docs/implementation docs/infrastructure docs/security docs/analytics docs/documentation

echo "📂 Directories created."

"""

def read_file(path):
    try:
        with open(path, 'r') as f:
            return f.read()
    except Exception as e:
        print(f"Error reading {path}: {e}")
        return ""

def append_file_block(script, file_path):
    content = read_file(file_path)
    if not content:
        return script
    
    script += f"echo 'Writing {file_path}...'\n"
    script += f"cat <<'EOF' > {file_path}\n"
    script += content
    # Ensure newline at end if missing to prevent EOF concatenation issues
    if not content.endswith('\n'):
        script += "\n"
    script += "EOF\n\n"
    return script

script_content = header

# List of patterns/directories to scan
base_dirs = [
    "agents/configs",
    "agents/prompts",
    "agents/specializations/saas",
    "agents/specializations/shopify",
    "agents/specializations/mobile",
    "agents/specializations/chrome-extension",
    "agents/specializations/ai-app",
    "agents/specializations/ecommerce",
    "workflows"
]

for directory in base_dirs:
    full_dir = os.path.join(cwd, directory)
    if os.path.exists(full_dir):
        for root, _, files in os.walk(full_dir):
            for file in files:
                if file.endswith(".json") or file.endswith(".md"):
                    # Get relative path
                    abs_path = os.path.join(root, file)
                    rel_path = os.path.relpath(abs_path, cwd)
                    script_content = append_file_block(script_content, rel_path)

script_content += 'echo "✅ AI Team successfully installed! Check README.md for usage."\n'

with open(output_file, 'w') as f:
    f.write(script_content)

print(f"Generated {output_file}")
